### ISSUE TITLE
Changing mode doesn't actually do anything 

### ISSUE THREAD

**Issue by ParanoidNemo** [Vanilla-OS/vanilla-prime-utility#48]
Hi, I'm on an Optimus laptop (dell Inspiron 7577) and after installation I'm automatically logged in with the on demand profile. Nvidia card works without problem, tested with various software that use it, but if I switch to discrete only profile, after the system does everything it needs too (without errors) and prompt me to reboot I'm still in the on-demand profile.
What can I do to solve or at least to give you more info so that you can check what's happening?

Kindly,

**Comment by mirkobrombin** [comment]
There is a bug that always show the on demand mode. I should have fixed with this commit https://github.com/Vanilla-OS/vanilla-tools/commit/a23d30a966fd2ab4923185a59ad3d3f6243447fb

Is this a new installation?
Can you provide the output for:

```bash
host-shell cat /etc/prime-discrete
```

please?

**Comment by ParanoidNemo** [comment]
No, is not a new installation, I've it installed the 30th of January, when the beta was released, but it being a beta I force updates pretty regularly with
`abroot upgrade -f`
last time I did it yesterday evening.

first command report
`cat: /etc/prime-discrete: No such file or directory`

second
` INFO  ABRoot Partitions:
         - Present: vos-b ◄
         - Future: vos-a
       
       Loaded Configuration: /etc/abroot/abroot.json
       
       Device Specifications:
         - CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
         - GPU:
       		- Intel Corporation HD Graphics 630 (rev 04)
       		- NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
         - Memory: 31839 MB
       
       ABImage:
         - Digest: sha256:4a00378fd5908398edcbe754ee91e9953d124ca8eb30737624d8ce30ac797061
         - Timestamp: 2024-02-09 18:55:04
         - Image: ghcr.io/vanilla-os/nvidia:main
       
       Kernel Arguments: quiet splash bgrt_disable $vt_handoff
       
       Packages:
         - Added: 
         - Removed: 
         - Unstaged: 
       , 
       Package agreement: false
`

**Comment by mirkobrombin** [comment]
Your next upgrade (once available) will add the missing file and fix the issue. Let me know if the problem persist. The build should be available in ~30 minutes.

**Comment by ParanoidNemo** [comment]
ok, updated and now is correctly set to discrete only, but I'm not sure that it's working correctly, because my secondary monitor (the HDMI is directly connected on the Nvidia card) is still not recognized by VanillaOS and doesn't power up.

**Comment by mirkobrombin** [comment]
Could be a different issue. What's the output for `nvidia.smi`, `cur-gpu` and `nrun cur-gpu`?

**Comment by ParanoidNemo** [comment]
first
```
Sun Feb 11 13:19:07 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P5     7W /  60W |      3MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

second
```
OpenGL version: 4.6 (Compatibility Profile) Mesa 23.3.4-1
OpenGL vendor: Intel
OpenGL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
```

third
```
OpenGL version: 4.6 (Compatibility Profile) Mesa 23.3.4-1
OpenGL vendor: Intel
OpenGL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
```

the strange thing is that blender recognize the Nvidia GPU for rendering so it is working, just seems to stay in on-demand because in every other distro is the same way, I've to prime in discrete only to have the external monitor work.
But if you prefer I'll open a different issue for this; if so I should open it here or in some other repo?

**Comment by mirkobrombin** [comment]
Open a new issue in the nvidia-image but I am not sure if there is something we can do, nvidia drivers are packaged by debian, our utility simply switch the PRIME profile and rebuild the initramfs.

**Comment by ParanoidNemo** [comment]
Ok I will do, but I really think is something with VanillaOS. Before it I was using Debian 12 with Nvidia drivers without any issue on the second monitor too

**Comment by ParanoidNemo** [comment]
sorry to bother you again here but I think that the problem is not solved.
Settings show me that I'm on discrete GPU but cur-gpu give me still "Intel" as a result, nrun cur-gpu instead gives me Nvidia; is it normal?
